{% set version = "333" %}
{% set flatversion = version.replace(".", "") %}

package:
  name: libsvm
  version: {{ version }}

source:
  url: https://github.com/cjlin1/libsvm/archive/v{{ flatversion }}.tar.gz
  sha256: ee898ca11cef85b09e059b278b3ab4ff58cd38f70169829e75b4a3cb9ddc5013

  patches:
    - python.patch
    # https://github.com/cjlin1/libsvm/pull/219
    - v333.patch
    - win32.patch  # [win32]

build:
  number: 1

outputs:
  - name: libsvm
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - make
    test:
      commands:
        - test -e $PREFIX/include/svm.h                           # [unix]
        - test -e $PREFIX/lib/libsvm.so                           # [linux]
        - test -e $PREFIX/lib/libsvm.so.3                         # [linux]
        - test -e $PREFIX/lib/libsvm.dylib                        # [osx]
        - test -e $PREFIX/lib/libsvm.3.dylib                      # [osx]
        - svm-train | grep 'Usage'                                # [unix]
        - svm-scale | grep 'Usage'                                # [unix]
        - svm-predict | grep 'Usage'                              # [unix]
        - svm-train | findstr "Usage"                             # [win]
        - svm-scale | findstr "Usage"                             # [win]
        - svm-predict | findstr "Usage"                           # [win]
        - if not exist %PREFIX%\\Library\\lib\\libsvm.dll exit 1  # [win]
  - name: libsvm-official
    build:
      noarch: python
      script: cd python; python -m pip install --no-deps --ignore-installed .
      skip: True  # [not linux]
    requirements:
      host:
        - {{ pin_subpackage('libsvm', max_pin="x.x.x") }}
        - pip
        - python
      run:
        - {{ pin_subpackage('libsvm', max_pin="x.x.x") }}
        - python
        - scipy
    test:
      imports:
        - libsvm
        - libsvm.svm
        - libsvm.svmutil
      commands:
        - pip check
      requires:
        - pip

about:
  home: https://github.com/cjlin1/libsvm
  license: BSD-3-Clause
  license_file: COPYRIGHT
  summary: A simple, easy-to-use, and efficient software for SVM classification and regression.

extra:
  recipe-maintainers:
    - 183amir
    - bkpoon
    - patricksnape
