{% set version = "335" %}
{% set flatversion = version.replace(".", "") %}

package:
  name: libsvm
  version: {{ version }}

source:
  url: https://github.com/cjlin1/libsvm/archive/v{{ flatversion }}.tar.gz
  sha256: f864faaf0e6606aa5eb89b48d76b77db43b501c3b0b1842ae036f9d754e675d9

  patches:
    - win32.patch  # [win32]

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make

test:
  commands:
    - test -e $PREFIX/include/svm.h                           # [unix]
    - test -e $PREFIX/lib/libsvm.so                           # [linux]
    - test -e $PREFIX/lib/libsvm.so.3                         # [linux]
    - test -e $PREFIX/lib/libsvm.dylib                        # [osx]
    - test -e $PREFIX/lib/libsvm.3.dylib                      # [osx]
    - svm-train | grep 'Usage'                                # [unix]
    - svm-scale | grep 'Usage'                                # [unix]
    - svm-predict | grep 'Usage'                              # [unix]
    - svm-train | findstr "Usage"                             # [win]
    - svm-scale | findstr "Usage"                             # [win]
    - svm-predict | findstr "Usage"                           # [win]
    - if not exist %PREFIX%\\Library\\lib\\libsvm.dll exit 1  # [win]

about:
  home: https://github.com/cjlin1/libsvm
  license: BSD-3-Clause
  license_file: COPYRIGHT
  summary: A simple, easy-to-use, and efficient software for SVM classification and regression.

extra:
  recipe-maintainers:
    - 183amir
    - bkpoon
    - patricksnape
